///////////////////
// USER CONSTANT //
///////////////////

// USER SIGN UP CONSTANT
export const SIGN_UP_REQUEST = "SIGN_UP_REQUEST";
export const SIGN_UP_SUCCESS = "SIGN_UP_SUCCESS";
export const SIGN_UP_FAIL = "SIGN_UP_FAIL";

// USER LOGIN CONSTANT
export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";

// USER LOGOUT CONSTANT
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAIL = "LOGOUT_FAIL";

// USER PROFILE LOAD CONSTNAT
export const LOAD_USER_REQUEST = "LOAD_USER_REQUEST";
export const LOAD_USER_SUCCESS = "LOAD_USER_SUCCESS";
export const LOAD_USER_FAIL = "LOAD_USER_FAIL";

// USER PROFILE UPDATE CONSTANT
export const UPDATE_USER_PROFILE_REQUEST = "UPDATE_USER_PROFILE_REQUEST";
export const UPDATE_USER_PROFILE_SUCCESS = "UPDATE_USER_PROFILE_SUCCESS";
export const UPDATE_USER_PROFILE_FAIL = "UPDATE_USER_PROFILE_FAIL";
export const UPDATE_USER_PROFILE_RESET = "UPDATE_USER_PROFILE_RESET";

// USER PASSWORD UPDATE CONSTANT
export const UPDATE_USER_PASSWORD_REQUEST = "UPDATE_USER_PASSWORD_REQUEST";
export const UPDATE_USER_PASSWORD_SUCCESS = "UPDATE_USER_PASSWORD_SUCCESS";
export const UPDATE_USER_PASSWORD_FAIL = "UPDATE_USER_PASSWORD_FAIL";
export const UPDATE_USER_PASSWORD_RESET = "UPDATE_USER_PASSWORD_RESET";



////////////////////////////
// CARS RELATED CONSTANTS //
////////////////////////////

// GET ALL CARS CONSTANT
export const CARS_GET_ALL_REQUEST = "CARS_GET_ALL_REQUEST";
export const CARS_GET_ALL_SUCCESS = "CARS_GET_ALL_SUCCESS";
export const CARS_GET_ALL_FAIL = "CARS_GET_ALL_FAIL";

// GET SINGLE CARS CONSTNAT
export const CARS_GET_SINGLE_REQUEST = "CARS_GET_SINGLE_REQUEST";
export const CARS_GET_SINGLE_SUCCESS = "CARS_GET_SINGLE_SUCCESS";
export const CARS_GET_SINGLE_FAIL = "CARS_GET_SINGLE_FAIL";


//CLEAR CONSTANT
export const CLEAR_ERRORS = "CLEAR_ERRORS";