///////////////////
// USER CONSTANT //
///////////////////

// 1) USER: SIGN UP CONSTANT
export const SIGN_UP_REQUEST = "SIGN_UP_REQUEST";
export const SIGN_UP_SUCCESS = "SIGN_UP_SUCCESS";
export const SIGN_UP_FAIL = "SIGN_UP_FAIL";

// 2) USER: LOGIN CONSTANT
export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";

// 3) USER: LOGOUT CONSTANT
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAIL = "LOGOUT_FAIL";

// 4) USER: PROFILE LOAD CONSTNAT
export const LOAD_USER_REQUEST = "LOAD_USER_REQUEST";
export const LOAD_USER_SUCCESS = "LOAD_USER_SUCCESS";
export const LOAD_USER_FAIL = "LOAD_USER_FAIL";

// 5) USER: PROFILE UPDATE CONSTANT
export const UPDATE_USER_PROFILE_REQUEST = "UPDATE_USER_PROFILE_REQUEST";
export const UPDATE_USER_PROFILE_SUCCESS = "UPDATE_USER_PROFILE_SUCCESS";
export const UPDATE_USER_PROFILE_FAIL = "UPDATE_USER_PROFILE_FAIL";
export const UPDATE_USER_PROFILE_RESET = "UPDATE_USER_PROFILE_RESET";

// 6) USER: ACCOUNT DELETE CONSTANT
export const DELETE_USER_ACCOUNT_REQUEST = "DELETE_USER_ACCOUNT_REQUEST";
export const DELETE_USER_ACCOUNT_SUCCESS = "DELETE_USER_ACCOUNT_SUCCESS";
export const DELETE_USER_ACCOUNT_FAIL = "DELETE_USER_ACCOUNT_FAIL";

// 7) USER: PASSWORD UPDATE CONSTANT
export const UPDATE_USER_PASSWORD_REQUEST = "UPDATE_USER_PASSWORD_REQUEST";
export const UPDATE_USER_PASSWORD_SUCCESS = "UPDATE_USER_PASSWORD_SUCCESS";
export const UPDATE_USER_PASSWORD_FAIL = "UPDATE_USER_PASSWORD_FAIL";
export const UPDATE_USER_PASSWORD_RESET = "UPDATE_USER_PASSWORD_RESET";

// 8) USER: FORGOT PASSWORD CONSTANT
export const FORGOT_USER_PASSWORD_REQUEST = "FORGOT_USER_PASSWORD_REQUEST";
export const FORGOT_USER_PASSWORD_SUCCESS = "FORGOT_USER_PASSWORD_SUCCESS";
export const FORGOT_USER_PASSWORD_FAIL = "FORGOT_USER_PASSWORD_FAIL";

// 9) USER: RESET PASSWORD CONSTANT
export const RESET_USER_PASSWORD_REQUEST = "RESET_USER_PASSWORD_REQUEST";
export const RESET_USER_PASSWORD_SUCCESS = "RESET_USER_PASSWORD_SUCCESS";
export const RESET_USER_PASSWORD_FAIL = "RESET_USER_PASSWORD_FAIL";



///////////////////
// USER CONSTANT //
///////////////////

// 1) ADMIN: GET ALL USERS CONSTANT
export const ADMIN_GET_ALL_USERS_REQUEST = "ADMIN_GET_ALL_USERS_REQUEST"
export const ADMIN_GET_ALL_USERS_SUCCESS = "ADMIN_GET_ALL_USERS_SUCCESS"
export const ADMIN_GET_ALL_USERS_FAIL = "ADMIN_GET_ALL_USERS_FAIL"

// 2) ADMIN: GET SINGLE USER CONSTANT
export const ADMIN_SINGLE_USER_REQUEST = "ADMIN_SINGLE_USER_REQUEST"
export const ADMIN_SINGLE_USER_SUCCESS = "ADMIN_SINGLE_USER_SUCCESS"
export const ADMIN_SINGLE_USER_FAIL = "ADMIN_SINGLE_USER_FAIL"

// 3) ADMIN: UPDATE USER ROLE CONSTANT
export const ADMIN_USER_ROLE_UPDATE_REQUEST = "ADMIN_USER_ROLE_UPDATE_REQUEST"
export const ADMIN_USER_ROLE_UPDATE_SUCCESS = "ADMIN_USER_ROLE_UPDATE_SUCCESS"
export const ADMIN_USER_ROLE_UPDATE_FAIL = "ADMIN_USER_ROLE_UPDATE_FAIL"

// 4) ADMIN: DELETE USER ACCOUNT CONSTANT
export const ADMIN_USER_ACCOUNT_DELETE_REQUEST = "ADMIN_USER_ACCOUNT_DELETE_REQUEST"
export const ADMIN_USER_ACCOUNT_DELETE_SUCCESS = "ADMIN_USER_ACCOUNT_DELETE_SUCCESS"
export const ADMIN_USER_ACCOUNT_DELETE_FAIL = "ADMIN_USER_ACCOUNT_DELETE_FAIL"

// 5) ADMIN: NEW OFFICE LOCATION CONSTANT
export const ADMIN_NEW_OFFICE_LOCATION_REQUEST = "ADMIN_NEW_OFFICE_LOCATION_REQUEST"
export const ADMIN_NEW_OFFICE_LOCATION_SUCCESS = "ADMIN_NEW_OFFICE_LOCATION_SUCCESS"
export const ADMIN_NEW_OFFICE_LOCATION_FAIL = "ADMIN_NEW_OFFICE_LOCATION_FAIL"
export const ADMIN_NEW_OFFICE_LOCATION_RESET = "ADMIN_NEW_OFFICE_LOCATION_RESET"

// 6) ADMIN: NEW OFFICE LOCATION CONSTANT
export const ADMIN_GET_OFFICES_LOCATION_REQUEST = "ADMIN_GET_OFFICES_LOCATION_REQUEST"
export const ADMIN_GET_OFFICES_LOCATION_SUCCESS = "ADMIN_GET_OFFICES_LOCATION_SUCCESS"
export const ADMIN_GET_OFFICES_LOCATION_FAIL = "ADMIN_GET_OFFICES_LOCATION_FAIL"

// 7) ADMIN: NEW CAR DETAILS CONSTANT
export const ADMIN_NEW_CAR_DETAILS_REQUEST = "ADMIN_NEW_CAR_DETAILS_REQUEST"
export const ADMIN_NEW_CAR_DETAILS_SUCCESS = "ADMIN_NEW_CAR_DETAILS_SUCCESS"
export const ADMIN_NEW_CAR_DETAILS_FAIL = "ADMIN_NEW_CAR_DETAILS_FAIL"

// 8) ADMIN: CAR DETAILS UPDATE CONSTANT
export const ADMIN_CAR_DETAILS_UPDATE_REQUEST = "ADMIN_CAR_DETAILS_UPDATE_REQUEST"
export const ADMIN_CAR_DETAILS_UPDATE_SUCCESS = "ADMIN_CAR_DETAILS_UPDATE_SUCCESS"
export const ADMIN_CAR_DETAILS_UPDATE_FAIL = "ADMIN_CAR_DETAILS_UPDATE_FAIL"
export const ADMIN_CAR_DETAILS_UPDATE_RESET = "ADMIN_CAR_DETAILS_UPDATE_RESET"

// 9) ADMIN: CAR DETAIL DELETE CONSTANT
export const ADMIN_CAR_DETAILS_DELETE_REQUEST = "ADMIN_CAR_DETAILS_REQUEST"
export const ADMIN_CAR_DETAILS_DELETE_SUCCESS = "ADMIN_CAR_DETAILS_SUCCESS"
export const ADMIN_CAR_DETAILS_DELETE_FAIL = "ADMIN_CAR_DETAILS_FAIL"

// 10) ADMIN: ALL ORDERS CONSTANT
export const ADMIN_ALL_USER_ORDER_REQUEST = "ADMIN_ALL_USER_ORDER_REQUEST"
export const ADMIN_ALL_USER_ORDER_SUCCESS = "ADMIN_ALL_USER_ORDER_SUCCESS"
export const ADMIN_ALL_USER_ORDER_FAIL = "ADMIN_ALL_USER_ORDER_FAIL"

//GET) ADMINs: USER ORDER UPDATE CONSTANT
export const ADMIN_USER_ORDER_UPDATE_REQUEST = "ADMIN_USER_ORDER_UPDATE_REQUEST"
export const ADMIN_USER_ORDER_UPDATE_SUCCESS = "ADMIN_USER_ORDER_UPDATE_SUCCESS"
export const ADMIN_USER_ORDER_UPDATE_FAIL = "ADMIN_USER_ORDER_UPDATE_FAIL"

// 11) ADMIN: USER ORDER DELETE CONSTANT
export const ADMIN_USER_ORDER_DELETE_REQUEST = "ADMIN_USER_ORDER_DELETE_REQUEST"
export const ADMIN_USER_ORDER_DELETE_SUCCESS = "ADMIN_USER_ORDER_DELETE_SUCCESS"
export const ADMIN_USER_ORDER_DELETE_FAIL = "ADMIN_USER_ORDER_DELETE_FAIL"


////////////////////////////
// CARS RELATED CONSTANTS //
////////////////////////////

// 1) GET ALL CARS CONSTANT
export const CARS_GET_ALL_REQUEST = "CARS_GET_ALL_REQUEST";
export const CARS_GET_ALL_SUCCESS = "CARS_GET_ALL_SUCCESS";
export const CARS_GET_ALL_FAIL = "CARS_GET_ALL_FAIL";

// 2) GET SINGLE CARS CONSTNAT
export const CARS_GET_SINGLE_REQUEST = "CARS_GET_SINGLE_REQUEST";
export const CARS_GET_SINGLE_SUCCESS = "CARS_GET_SINGLE_SUCCESS";
export const CARS_GET_SINGLE_FAIL = "CARS_GET_SINGLE_FAIL";

////////////////////////////
// CARS RELATED CONSTANTS //
////////////////////////////

// 1) ORDER: NEW ORDER CONSTANT
export const USER_NEW_ORDER_REQUEST  = 'USER_NEW_ORDER_REQUEST'
export const USER_NEW_ORDER_SUCCESS  = 'USER_NEW_ORDER_SUCCESS'
export const USER_NEW_ORDER_FAIL  = 'USER_NEW_ORDER_FAIL'

// 2) ORDER: USER ALL ORDERS CONSTANT
export const USER_ALL_ORDER_REQUEST  = 'USER_ALL_ORDER_REQUEST'
export const USER_ALL_ORDER_SUCCESS  = 'USER_ALL_ORDER_SUCCESS'
export const USER_ALL_ORDER_FAIL  = 'USER_ALL_ORDER_FAIL'

// 3) ORDER: USER SINGLE ORDER CONSTANT
export const USER_SINGLE_ORDER_DETAIL_REQUEST  = 'USER_SINGLE_ORDER_DETAIL_REQUEST'
export const USER_SINGLE_ORDER_DETAIL_SUCCESS  = 'USER_SINGLE_ORDER_DETAIL_SUCCESS'
export const USER_SINGLE_ORDER_DETAIL_FAIL  = 'USER_SINGLE_ORDER_DETAIL_FAIL'


//CLEAR CONSTANT
export const CLEAR_ERRORS = "CLEAR_ERRORS";