import User from '../models/User.js';
import OfficeLocation from '../models/OfficeLocation.js';
import Order from '../models/Order.js';
import Car from '../models/Car.js';
import Payment from '../models/Payment.js';
import paytm from 'paytmchecksum';
import https from 'https';
import uuid from 'uuid'
import ErrorHandler from '../utils/errorHandler.js';
import CatchAsync from '../middlewares/catchAsync.js'
import mail from '../utils/sendEmail.js';